### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos _issues_ nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by phegraphic** [comment]
Muy buenas chic@s! Me presento un poco:
+++++++++++++++++++++++++++++++++++++++++++++++++++++
Soy Carlos Fernandez (Phegraphic) apasionado del Diseño grafico, del Diseño web y del Arte. Me encanta ver las cositas bien diseñadas (al pixel), que sea todo muy funcional y bello, por eso quiero controlar Javascript para poder realizar validaciones perfectas, modales a mi gusto, tooltips como el que se toma un cafe. Controlar cualquier tipo de front es mi objetivo, la Excelencia Gráfica es la meta.
+++++++++++++++++++++++++++++++++++++++++++++++++++++
Podeis ver cositas mias y seguirme en mi web: www.phegraphic.com

Pd: este <textarea> tiene demasiada interlinea o me lo parece a mi... :)

**Comment by robertoSoteres** [comment]
Muy buenas tardes a tod@s!
Mi nombre es Roberto Soteres, soy un **desarrollador front-end** movido por las _ganas de aprender_ cosas nuevas y _no quedarme estancado_. Con este curso, se nos abre un mundo de posibilidades que creo, nos aportará y enriquecerá muchísimo. Además, y como segundo objetivo, quiero dominar el mundo, como dijo el Dr. Maligno:

> Mata al “Bueno” , no te enrolles, no le cuentes nada de tu malvado plan o de tus debilidades antes de  matarlo, de lo contrario extrañamente se escapara y te desbaratara los planes.


Pero esto, ya es otro tema.

**Comment by LeylaVieira** [comment]
Hola! soy Leyla y actualmente trabajo como desarrolladora front-end en una editorial. Empecé estudiando programación (java, .net), sin embargo, poco a poco me fue interesando el desarrollo de sitios web. Al tener una base sobre desarrollo me fue fácil entender ciertas estructuras en JavaScript, pero ha ido evolucionando que siento que hay cosas que se me escapan. Seguro y tendré *manías* a la hora de programar, así que con este curso espero poder corregir esos **horrores** y seguir creciendo... por último, sólo me queda por decir:
```javascript
console.log('Hola mundo JavaScript!');
```

**Comment by RoseveltBarahona** [comment]
hola a todos soy Rosevelt,  Actualmente me dedico a la maquetación web, y la empresa me ha **"recomendado"** ;)  meter mano a frameworks/librerias de javascript.  Pero antes que nada deseo ir en orden y empezar con javascript como base de todo, antes de coger malas costumbres.
Nunca he programado así que estoy muy motivado para por fin entender de que va eso ;) .
saludos!

**Comment by Jluismuga** [comment]
Buenas tardes a todos!!
Soy Luis, actualmente trabajo en un malvado laboratorio farmacéutico, me ocupo de extender los virus (biológicos...) por tantos vagones de metro como me sea posible en mi jornada laboral, tosiendo a la gente encima y todo eso; también me ocupo del desarrollo del CRM de la empresa, además de múltiples aplicaciones para todos los departamentos de la empresa y red de ventas. Mi entorno de trabajo es estrictamente cliente-servidor utilizando tecnología Progress, muy apartada de lo que se estudia en este curso. Me interesa aprender esta tecnología "nueva" para mí, creo que podré sacarle mucho partido en mi trabajo actual o futuro. Aunque veo que me va a costar bastante arrancar, espero ir cogiendo ritmo!!

Un saludo!!

**Comment by jjfp30** [comment]
Hola muy buenas tardes a todos!!
Me llamo Jesús actualmente trabajo como desarrollador front-end en una empresa q se llama Oneclick.., en la empresa me están metiendo en proyectos con javascript.. y claro he trabajado con ello metiendo mano en scripts desarrollados por otras personas y con alguna líbreria pero necesito entenderlo todo bien y coger fluidez para poder mejorar y afrontar todos los proyectos en los que me vayan metiendo. Me interesa mucho el curso y estoy motivado, espero que salga todo muy bien.
Un saludito.

**Comment by crispinh2o** [comment]
Buenas noches a todos!! 

Nunca es tarde si la dicha es buena, mi nombre es Crispín y soy un diseñador gráfico que empezó odiando el código y ahora lo ama. Desde hace años trabajo como maquetador web y como el cuerpo me pide más quiero aprender a hacer "magia".

Un placer... nos vemos el próximo día!!!

**Comment by MercedesNavarro** [comment]
Hola chicos!
Me llamo Merce y actualmente trabajo en una consultora de comercio electrónico. Siempre me ha gustado la maquetación web aunque hasta que entré en este trabajo no me fue posible dedicarme a ello. Así que fui realizando diversos cursos de programación y cada vez me ha ido gustando más.
Y aquí estoy, deseando aprender y mejorar cada día ;)
Saludos!

**Comment by UlisesGascon** [comment]
Ahora que nos conocemos todos... doy por cerrado este issue :-)

**Feliz puente!**
