### ISSUE TITLE
Issue_para_Ulises_01

### ISSUE THREAD

**Issue by phegraphic** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#10]
Hola Ulises soy Carlos.

Sigo con mi DOM aqui liado y no consigo resolver un pequeño problema. Mañana en la clase lo vemos en un segundo, no hace falta que pierdas el tiempo con semejante tonteria. El mini-problema es el siguiente:

De la pagina http://phegraphic.com/prueba/ quiero coger el div con id = "myModal" y cortarlo y pegarlo justo donde acaba el div con id = "header-space" para que el modal ocupe todo. Tan simple como esto.

Los logro atacar con el codigo que pego seguidamente, pero luego no consigo el cut & paste. He intentado con appendChild e innerHTML sin exito.

var modal = document.getElementById("myModal");
var destino = document.getElementById("header-space");
console.log(modal);
console.log(destino);

+++++++++++++
Gracias de antemano.

**Comment by UlisesGascon** [comment]
Creo que con esto... valdría... 😄 

```javascript
var modal = document.getElementById("myModal");
var destino = document.getElementById("header-space");

insertAfter(destino, modal);

function insertAfter(nodoExistente, nuevoNodo) {
    referenceNode.parentNode.insertBefore(nuevoNodo, nodoExistente.nextSibling);
}
```

**Comment by phegraphic** [comment]
Hola Ulises.
No me funcionaba el codigo que me pasaste (I dont know why) y aplicando el **insertBefore** de una forma mas sencilla si lo logre. He conseguido entender como funciona los nodos para manejar los del DOM y estoy que doy saltos de alegria. Aquí esta el codigo utilizado:

var modal = document.getElementById("myModal");
var destino = document.getElementById("header-space");
var parent_div = destino.parentNode;
parent_div.insertBefore(modal, destino);
