### ISSUE TITLE
Duda clase anterior

### ISSUE THREAD

**Issue by robertoSoteres** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#12]
Hola buenas! Estoy mirando lo que hicisteis la semana pasada, revisando los arrays y eso... y me surge alguna duda!
La primera es la siguiente: En el métido forEach(), le pasas a la función logger los parámetros element, index, array... Peeeero lo que no entiendo, es como se identifica cada variable con lo que es... el forEach() es así por defecto? o como va?

**Comment by UlisesGascon** [comment]
Justo lo vimos en clase con algunos ejemplos que no están subidos... pero ahora repasamos :)

**Comment by robertoSoteres** [comment]
Ahh vale, gracias! 💃
