### ISSUE TITLE
maquina espendedora

### ISSUE THREAD

**Issue by robertoSoteres** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#13]
Hola Ulises!
Podrías poner los dos primeros puntos de la maquina espendedora xfaa??
gracias! :D

**Comment by UlisesGascon** [comment]
Hola @robertoSoteres ... he subido hasta el 3 incluido para dar más visión de conjunto :P

**Comment by robertoSoteres** [comment]
genial! muchas gracias! :)
