### ISSUE TITLE
Imagen carátula

### ISSUE THREAD

**Issue by robertoSoteres** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#16]
Ulises!
Tengo un problemilla con la caratula... no la veo en la api.. y estoy intentando cogerla de la pagina de amazon... peeeeeeeeero no consigo que me funcione.... como podría hacerlo? Lo más "sensato" que se me ha ocurrido ha sido esto:

datos.results[i].amazon_product_url.getElementById("imgBlkFront");

**Comment by LeylaVieira** [comment]
Hi Roberto! la portada del libro la tienes en la API con esta estructura: [GET /lists/{date}/{list}.json](http://developer.nytimes.com/books_api.json#/Console/GET/lists/%7Bdate%7D/%7Blist%7D.json)
Dentro, tienes el atributo llamado book_image, que es la ruta de la imagen.

**Comment by robertoSoteres** [comment]
Muchas gracias Leyla! Me estaba volviendo loco!!
