### ISSUE TITLE
Proyecto

### ISSUE THREAD

**Issue by robertoSoteres** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#18]
Hola buenas Ulises!!
Oye, tengo una pequeña duda ( que no tengo ni **** idea si lo puedo hacer así, vaya xD). 
No se si recuerdas el proyecto que quería hacer.. El editor de texto enriquecido y esas cosas. Había pensado hacer la carga de archivos y el "commit" con Node. El problema es, que no se si es conveniente o no hacerlo y espero tu orientación como agua de mayo! jajajaja

Gracias! :D

PD: No se sabe nada aún de la fecha de entrega del proyecto???

**Comment by UlisesGascon** [comment]
Buenas @robertoSoteres! Veo que vas por buen camino! :)

Vamos por partes... ¿Realmente necesitas un backend completo? Es decir... si lo que necesitas es poder enviar/recuperar información... tienes métodos alternativos que pueden ayudarte mucho como [almacenamiento en cliente con HTML5](https://www.html5rocks.com/en/tutorials/offline/storage/). Aunque yo personalmente te recomendaría utilizar [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). En principio te permite almacenar clave/valor, pero puedes "hackear" el concepto si utilizas [JSON.parse()](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/JSON/parse) y [JSON.stringify()](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/JSON/stringify) para almacenar objetos enteros (con sus propiedades).

Creo que además [esta guía de MDN](https://developer.mozilla.org/en-US/docs/Rich-Text_Editing_in_Mozilla) puede ayudarte un poco con la arquitectura y sacar partido a muchas etiquetas con las que no solemos estar familiarizados para hacer editores de texto.

Os digo la fecha de entrega esta semana sin falta. :)

Un abrazo!!
