### ISSUE TITLE
Git Magic (Ben Lynn)

### ISSUE THREAD

**Issue by crispinh2o** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#2]
Aquí dejo el pdf que comenté en clase ; )
[Git_Magic.pdf](https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed7/files/625894/Git_Magic.pdf)

**Comment by LeylaVieira** [comment]
Muchas gracias Crispín!  :smiley:
