### ISSUE TITLE
Ayuda con GitHub

### ISSUE THREAD

**Issue by LeylaVieira** [Fictizia/Curso-JS-para-desarrolladores-web_ed7#3]
Hola a todos! como sospechaba estoy perdida en este entorno, así que ¿qué pasos he de seguir para crear la carpeta en el repositorio? Lo intenté ayer, pero creé un archivo en lugar de una carpeta (espero que pueda eliminarse). He descargado la aplicación para escritorio, sin embargo, tampoco encuentro el camino :confounded:

**Comment by phegraphic** [comment]
Hola Leyla. Yo tambien estoy con la aplicacion de escritorio "Github Desktop" ya que me resulta mas comodo que la consola. En el proceso de instalacion me pidio los datos de usuario de Github y el programa se queda con ellos como predeterminados. Despues de esto ya solo tienes que sincronizar y te creara una copia de todo el repositorio en tu ordenador. Para subir una carpeta con un archivo de prueba dentro, la creas en en ese mismo directorio que el programa te ha clonado y descargado a tu maquina. En cuanto la creas el programa ya detecta que hay un archivo nuevo, haces el commit con un comentario y luego haces el Sync para que se suba realmente a Github... parece facil pero no lo es tanto jajaj

Espero que te sirva de ayuda.

**Comment by LeylaVieira** [comment]
Hola phegraphic! muchas gracias por tus indicaciones, creo que lo he conseguido :satisfied:

**Comment by RoseveltBarahona** [comment]
hola leyla, creo que has hecho un fork ( que es como una copia a partir de algo ya existente creo =P  ).
si te das cuenta  hay dos urls:
https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed7
que seria **la oficial del curso**.

y esta:
https://github.com/LeylaVieira/Curso-JS-para-desarrolladores-web_ed7
que es una como una copia  **PERO** en tu cuenta de github,  pero pone claramente "_forked from Fictizia/Curso-JS-para-desarrolladores-web_ed7"_

entonces, algo anda mal. ¿se como arreglarlo? No.
Lamento no poder ayudar más. 

pd: Quizás deberías volver a intentar clonar el repositorio "oficial" en tu ordenador y mover tus archivos ahí.

saludos.

**Comment by LeylaVieira** [comment]
Hola Rosevelt! gracias por tu explicación. A partir de ello he intentado realizar nuevamente la subida de mis archivos, sin embargo cuando le doy a Sync, aparece este error:

![image](https://cloud.githubusercontent.com/assets/24264883/20921249/8b74249e-bba3-11e6-8c36-c3f379bc8807.png)

Así que de momento creo que no moveré nada más, no vaya a ser que la líe :confused:

**Comment by UlisesGascon** [comment]
Hola a todos!

En la próxima clase repasaremos todo el flujo de trabajo con GitHub Desktop Client... pero hasta entonces... voy a intentar arrojar algo de luz :-)

@RoseveltBarahona, @phegraphic y @crispinh2o han logrado subir commits a nuestro repositorio, como podéis ver en la [historia del proyecto](https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed7/commits/master)

@LeylaVieira por lo que puedo ver en los [gráficos del proyeto](https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed7/network) @RoseveltBarahona tiene razón y has estado trabajando sobre [este fork](https://github.com/LeylaVieira/Curso-JS-para-desarrolladores-web_ed7) del proyecto. En principio es como si trabajaras sobre una copia del proyecto y no con el proyecto en sí. No te preocupes por eso de momento. Los commits que habías subido con las [soluciones del ejercicio 1 al 11](https://github.com/LeylaVieira/Curso-JS-para-desarrolladores-web_ed7/commit/7332b78c161f092207508ee4aff263b8ca25e119) están. Al final has logrado subir tus cambios pero a la copia del proyecto (fork) y no al proyecto donde estamos todos (usuario Fictizia). 

En principio para poder sincronizarte con el repositorio correcto solo necesitarias pinchar en el botón verde (Clone or Download) de [este enlance](https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed7) y pinchar después en "Open in Desktop" para que añada nuestro repositorio a tu cliente de GitHub para el escritorio y volver a crear tu carpeta con las soluciones y crear un commit.

O si prefieres podemos hacerlo en clase el próximo día... ;-)

Y por último no os desaniméis... Git/Github es un sistema de control de versiones con muchas opciones y maneras de trabajar... esa flexibilidad es lo que hace que tenga una curva de aprendizaje un poco particular. A lo largo del curso nos haremos con el! 👍 

**Feliz puente a todos!**

**Comment by UlisesGascon** [comment]
Hola a todos!

@LeylaVieira ha logrado subir sus soluciones utilizando un pull request... esta es otra forma válida para subir commits a repositorios. Los pull requests suelen utilizarse con proyectos donde no podemos aportar directamente al no ser colaboradores o bien en proyectos donde se decide gestionar así las contribuciones. 

[Este es el pull request en cuestión](https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed7/pull/5)
